export enum UserStatus {
  ACTIVE = "ACTIVE",
  BLOCKED = "BLOCKED",
  PENDING = "PENDING",
  ACCESS_REQUESTED = "ACCESS_REQUESTED",
  PENDING_INVITE = "PENDING_INVITE",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
  REJECTED = "REJECTED",
  PLACED = "PLACED",
  IN_PROCESS = "IN_PROCESS",
}
