import "./load.env";
import { z } from "zod";

const envSchema = z.object({
  PORT: z.string().transform(Number),
  NODE_ENV: z.enum(["development", "production", "test"]).default("development"),
  CLIENT_URL: z.string().default("http://localhost:3000"),
  MONGODB_URI: z.string().nonempty("MONGODB_URI is required"),
  JWT_ACCESS_SECRET: z.string().nonempty("JWT_ACCESS_SECRET is required"),
  JWT_ACCESS_EXPIRES_IN: z.string(),
  JWT_REFRESH_SECRET: z.string().nonempty("JWT_REFRESH_SECRET is required"),
  JWT_REFRESH_EXPIRES_IN: z.string(),
  COOKIE_MAX_AGE_MS: z.string().transform(Number).default("1800000"),
  REFRESH_COOKIE_MAX_AGE_MS: z.string().transform(Number).default("604800000"), // 7 days
  EMAIL_HOST: z.string().nonempty("EMAIL_HOST is required"),
  EMAIL_PORT: z.string().transform(Number),
  EMAIL_USER: z.string().nonempty("EMAIL_USER is required"),
  EMAIL_PASS: z.string().nonempty("EMAIL_PASS is required"),
  EMAIL_FROM: z.string().default("CareerHub <no-reply@careerhub.com>"),
  FRONTEND_URL: z.string().default("http://localhost:3000"),
  LIVEKIT_URL: z.string().url(),
  LIVEKIT_API_KEY: z.string().optional(),
  LIVEKIT_API_SECRET: z.string().optional(),

  // Tavus optional Avatar
  AI_AVATAR_ENABLED: z.enum(["true", "false"]).default("false"),
  TAVUS_API_KEY: z.string().optional(),
  TAVUS_REPLICA_ID: z.string().optional(),

  CARTESIA_API_KEY: z.string().optional(),
  CARTESIA_VOICE_ID: z.string().default("db6b0ed5-d5d3-463d-ae85-518a07d3c2b4"),
  CARTESIA_MODEL_ID: z.string().default("sonic-3.5"),
  DEEPGRAM_API_KEY: z.string().min(1,"DEEPGRAM_API_KEY is required"),
  STT_ENDPOINTING_MS: z.coerce.number().default(2500),
  USE_LOCAL_LLM: z.coerce.boolean().default(false),
  AI_PROVIDER: z.enum(["OLLAMA", "GEMINI", "GROQ", "OPENAI"]).optional(),
  AI_LLM_PROVIDER: z.enum(["OLLAMA", "GEMINI", "GROQ", "OPENAI"]).optional(),
  AI_QUESTION_PROVIDER: z.enum(["OLLAMA", "GEMINI", "GROQ", "OPENAI"]).optional(),
  AI_QUESTION_MODEL: z.string().optional(),
  AI_QUESTION_BASE_URL: z.string().optional(),
  AI_QUESTION_TEMPERATURE: z.coerce.number().default(0.2),
  AI_QUESTION_MAX_TOKENS: z.coerce.number().default(48),
  AI_QUESTION_TIMEOUT_MS: z.coerce.number().default(15000),
  AI_EVALUATION_PROVIDER: z.enum(["OLLAMA", "GEMINI", "GROQ", "OPENAI"]).optional(),
  AI_EVALUATION_MODEL: z.string().optional(),
  AI_EVALUATION_BASE_URL: z.string().optional(),
  AI_EVALUATION_TEMPERATURE: z.coerce.number().default(0.1),
  AI_EVALUATION_MAX_TOKENS: z.coerce.number().default(160),
  AI_EVALUATION_TIMEOUT_MS: z.coerce.number().default(90000),
  AI_FULL_EVALUATION_PROVIDER: z.enum(["OLLAMA", "GEMINI", "GROQ", "OPENAI"]).optional(),
  AI_FULL_EVALUATION_MODEL: z.string().optional(),
  AI_FULL_EVALUATION_BASE_URL: z.string().optional(),
  AI_FULL_EVALUATION_TEMPERATURE: z.coerce.number().default(0.1),
  AI_FULL_EVALUATION_MAX_TOKENS: z.coerce.number().default(4000),
  AI_FULL_EVALUATION_TIMEOUT_MS: z.coerce.number().default(120000),
  AI_LLM_TIMEOUT_MS: z.coerce.number().default(25000),
  OLLAMA_BASE_URL: z.string().default("http://127.0.0.1:11434"),
  GEMINI_API_KEY: z.string().optional(),
  GROQ_API_KEY: z.string().optional(),
  OPENAI_API_KEY: z.string().optional(),
  LIVEKIT_TOKEN_TTL: z.string().default("2h"),
  RABBITMQ_PREFETCH: z.coerce.number().default(1),
  RABBITMQ_URL: z.string().default("amqp://127.0.0.1")
});

export const env = envSchema.parse(process.env);
