export enum CandidateQuestionCategory {
  CLARIFICATION = 'CLARIFICATION',
  INTERVIEW_PROCESS = 'INTERVIEW_PROCESS',
  UNKNOWN_INFO = 'UNKNOWN_INFO',
  COMPANY_OR_ROLE = 'COMPANY_OR_ROLE',
  OFF_TOPIC = 'OFF_TOPIC'
}