export enum CandidateUtteranceIntent {
  HESITATION = 'HESITATION',
  EXPLICIT_DONT_KNOW = 'EXPLICIT_DONT_KNOW',
  CANDIDATE_QUESTION = 'CANDIDATE_QUESTION',
  REPEAT_QUESTION = 'REPEAT_QUESTION',
  PAUSE_REQUEST = 'PAUSE_REQUEST',
  NORMAL_ANSWER = 'NORMAL_ANSWER'
}