export enum FeatureKey {
  NOTICE_BOARD = 'NOTICE_BOARD',
  BROADCAST_EMAILS = 'BROADCAST_EMAILS',
  BASIC_RESUME_BUILDER = 'BASIC_RESUME_BUILDER',
  FULL_AI_RESUME_BUILDER = 'FULL_AI_RESUME_BUILDER',
  MOCK_INTERVIEW = 'MOCK_INTERVIEW',
  ADVANCED_ANALYTICS = 'ADVANCED_ANALYTICS',
  INTERVIEW_CALENDAR_VIEW = 'INTERVIEW_CALENDAR_VIEW'
}
