export enum InterviewIntegrityEventType {
  TAB_SWITCH = 'TAB_SWITCH',
  WINDOW_BLUR = 'WINDOW_BLUR',
  WINDOW_FOCUS = 'WINDOW_FOCUS',
  CAMERA_DISABLED = 'CAMERA_DISABLED',
  CAMERA_ENABLED = 'CAMERA_ENABLED',
  MIC_DISABLED = 'MIC_DISABLED',
  MIC_ENABLED = 'MIC_ENABLED',
  PAGE_HIDDEN = 'PAGE_HIDDEN',
  PAGE_VISIBLE = 'PAGE_VISIBLE',
  FACE_NOT_DETECTED = 'FACE_NOT_DETECTED',
  MULTIPLE_FACES_DETECTED = 'MULTIPLE_FACES_DETECTED',
  GAZE_DEVIATION = 'GAZE_DEVIATION',
}
