export enum InterviewPhase {
  NOT_STARTED = 'NOT_STARTED',
  INTRO = 'INTRO',
  ASKING_QUESTION = 'ASKING_QUESTION',
  EVALUATING = 'EVALUATING',
  ASKING_FOLLOW_UP = 'ASKING_FOLLOW_UP',
  CLOSING = 'CLOSING',
  COMPLETED = 'COMPLETED',
}