export enum InterviewStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULE_REQUESTED = 'RESCHEDULE_REQUESTED',
  CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED'
}
