import { ICreateSystemNotificationUseCase, CreateSystemNotificationDto } from "../interfaces/ICreateSystemNotification.usecase";
import { INotificationRepository } from "@domain/repositories/INotificationRepository";
import { Notification } from "@domain/entities/Notification";

export class CreateSystemNotificationUseCase implements ICreateSystemNotificationUseCase {
    constructor(private readonly notificationRepository: INotificationRepository) {}

    async execute(data: CreateSystemNotificationDto): Promise<void> {
        const notification = new Notification(
            "", // ID is auto-generated by DB
            data.recipientId,
            data.role,
            data.title,
            data.message,
            data.type,
            false, // isRead starts false
            data.link || null,
            new Date(),
            new Date()
        );

        await this.notificationRepository.create(notification);
    }
}
